/** Supabase table and column names (matches remote schema). */
export const TABLES = {
  workspaces: "workspaces",
  workspaceMembers: "workspace_members",
  employees: "employees",
  preferences: "preferences",
  shifts: "shifts",
  branchSettings: "branch_settings",
  timeLogs: "time_logs",
  shiftTemplates: "shift_templates",
  leaveRequests: "leave_requests",
  leaveBalances: "leave_balances",
  hrDocuments: "hr_documents",
  messages: "messages",
  pushSubscriptions: "push_subscriptions",
  notificationPreferences: "notification_preferences",
  shiftSwapRequests: "shift_swap_requests",
  schedulePublications: "schedule_publications",
} as const;

export const COLS = {
  workspaceId: "workspace_id",
  employeeId: "employee_id",
  shiftDate: "date",
  startTime: "start_time",
  endTime: "end_time",
  shiftId: "shift_id",
  clockIn: "clock_in",
  clockOut: "clock_out",
  actualHours: "actual_hours",
  overtimeHours: "overtime_hours",
  clockInLat: "clock_in_lat",
  clockInLng: "clock_in_lng",
  clockOutLat: "clock_out_lat",
  clockOutLng: "clock_out_lng",
  leaveType: "leave_type",
  startDate: "start_date",
  endDate: "end_date",
  recipientId: "recipient_id",
  senderId: "sender_id",
} as const;
